ordering items took 0:00:01
Tests considered 69 and ignored 320
2023-12-29 01:32:17,718 T0000: NOTICE WORKER = gw6
2023-12-29 01:32:17,718 T0000: NOTICE using testbed file /data/work/logs/docker-master-443064-l2/testbed_1_1_3.yaml
2023-12-29 01:32:17,718 T0000: NOTICE Execution Start Time: 2023-12-29 01:32:17.717185
2023-12-29 01:32:17,719 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-443064-l2/gw6
2023-12-29 01:32:18,259 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-29 01:32:18,259 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 40.1%
2023-12-29 01:32:18,259 T0000: NOTICE ROOT_PATH: /repo
2023-12-29 01:32:18,259 T0000: NOTICE Python: 3.8.10
2023-12-29 01:32:18,259 T0000: NOTICE Topology unknown: D1T1:4
2023-12-29 01:32:18,259 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-29 01:32:18,259 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-29-01-29-47 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-443064-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-443064-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-443064-l2 --noop --feature-group master
2023-12-29 01:32:18,895 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2023-12-29 01:32:18,895 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-29 01:32:18,895 T0000: WARN  Registering Topology
2023-12-29 01:32:18,911 T0000: INFO  Connecting all devices
2023-12-29 01:32:18,914 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/5', '1/6', '1/7', '1/8'] skip: False
2023-12-29 01:32:19,114 T0002: INFO  [D1-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2023-12-29 01:32:19,115 T0002: INFO  [D1-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2023-12-29 01:32:19,931 T0000: INFO  TG Scapy Init
2023-12-29 01:32:19,934 T0000: INFO  TG Base Init skip: False
2023-12-29 01:32:19,944 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-29 01:32:20,080 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_29_01_32_19_974581/gw6/default.log
2023-12-29 01:32:20,086 T0000: DEBUG REQ: tg_connect(port_list=['1/5', '1/6', '1/7', '1/8'])
2023-12-29 01:32:24,465 T0002: DEBUG [D1-V2] Connected ...
2023-12-29 01:32:25,285 T0002: INFO  [D1-V2] Prompt at the connection start: 'admin@V2:~$' 
2023-12-29 01:32:25,287 T0002: AUDIT [D1-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-29 01:32:25,695 T0002: INFO  [D1-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-29 01:32:25,951 T0002: INFO  [D1-V2]  01:32:25 up 21 days,  2:35,  1 user,  load average: 13.83, 16.53, 11.30
2023-12-29 01:32:25,951 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:25,961 T0002: AUDIT [D1-V2] cat /proc/uptime
2023-12-29 01:32:26,366 T0002: INFO  [D1-V2] FCMD: cat /proc/uptime
2023-12-29 01:32:26,623 T0002: INFO  [D1-V2] 1823707.16 143794150.13
2023-12-29 01:32:26,623 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:26,625 T0002: INFO  [D1-V2] UPTIME: 1823707.16
2023-12-29 01:32:26,628 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:27,035 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:27,503 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8"}, "status": 1}
2023-12-29 01:32:27,512 T0000: INFO  TG Connection: Success
2023-12-29 01:32:27,512 T0000: INFO  TG Connect...done
2023-12-29 01:32:27,697 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:32:27,697 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:27,700 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:27,702 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:27,702 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:32,706 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:33,113 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:33,724 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:32:33,724 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:33,727 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:33,729 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:33,729 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:38,735 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:39,143 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:39,804 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:32:39,804 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:39,806 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:39,807 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:39,807 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:44,809 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:45,216 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:45,876 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:32:45,876 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:45,879 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:45,881 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:45,882 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:50,886 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:51,294 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:51,955 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:32:51,956 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:51,958 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:51,961 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:51,961 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:56,966 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:57,374 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:58,035 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:32:58,035 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:32:58,038 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:58,040 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:58,040 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:03,046 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:03,454 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:04,115 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:04,115 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:04,118 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:04,120 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:04,121 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:09,126 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:09,534 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:10,145 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:10,145 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:10,148 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:10,150 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:10,150 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:15,154 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:15,560 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:16,168 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:16,168 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:16,170 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:16,170 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:16,170 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:21,176 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:21,584 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:22,195 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:22,195 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:22,198 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:22,199 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:22,199 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:27,202 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:27,609 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:28,269 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:28,269 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:28,271 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:28,272 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:28,272 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:33,278 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:33,686 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:34,297 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:34,298 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:34,300 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:34,303 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:34,303 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:39,308 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:39,715 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:40,375 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:40,375 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:40,378 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:40,379 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:40,379 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:45,385 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:45,793 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:46,454 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:46,454 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:46,457 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:46,459 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:46,459 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:51,462 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:51,870 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:52,531 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:52,531 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:52,534 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:52,536 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:52,536 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:57,542 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:57,950 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:58,561 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:33:58,561 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:33:58,564 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:58,567 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:58,567 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:03,570 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:03,977 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:04,587 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:34:04,587 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:34:04,590 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:04,592 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:04,592 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:09,597 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:10,002 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:10,760 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:34:10,760 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:34:10,762 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:10,763 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:10,763 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:15,769 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:16,176 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:16,838 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:34:16,838 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:34:16,841 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:16,843 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:16,843 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:21,845 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:22,250 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:22,961 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-29 01:34:22,961 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:34:22,964 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:22,966 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:22,966 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:27,973 T0002: ERROR [D1-V2] Failed to read hostname from vtysh - assuming sonic
2023-12-29 01:34:27,975 T0002: INFO  [D1-V2] Base Prompt: sonic
2023-12-29 01:34:27,975 T0002: DEBUG [D1-V2] Wait for system ready Ref: 866
2023-12-29 01:34:28,380 T0002: INFO  [D1-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-29 01:34:28,635 T0002: INFO  [D1-V2] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-29 01:34:28,636 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:34:28,640 T0002: WARN  [D1-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-29 01:34:28,641 T0002: INFO  [D1-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-29 01:34:33,674 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-29 01:34:33,677 T0002: INFO  [D1-V2] 
2023-12-29 01:34:33,677 T0002: INFO  [D1-V2] Remote CMD: 'show platform summary'
2023-12-29 01:34:33,677 T0002: INFO  [D1-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]     from show.main import cli
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]     if is_gearbox_configured():
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]     app_db.connect(app_db.APPL_DB)
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-29 01:34:33,678 T0002: INFO  [D1-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2] 
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2] Remote CMD: 'sudo show interfaces status '
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-29 01:34:33,679 T0002: INFO  [D1-V2]     from show.main import cli
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]     if is_gearbox_configured():
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]     app_db.connect(app_db.APPL_DB)
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-29 01:34:33,680 T0002: INFO  [D1-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-29 01:34:33,681 T0002: INFO  [D1-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:33,681 T0002: INFO  [D1-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-29 01:34:33,681 T0002: INFO  [D1-V2] 
2023-12-29 01:34:33,681 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-29 01:34:33,682 T0002: ERROR [D1-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-29 01:34:33,682 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-29 01:34:33,683 T0002: ERROR [D1-V2] Failed to connect to device
2023-12-29 01:34:33,684 T0000: ERROR Failed to connect (['V2'])
2023-12-29 01:34:33,684 T0000: INFO  --FINISH--RUN--4 @559
