2024-01-06 23:08:42,707 T0017: WARN  #### gw2  
2024-01-06 23:08:42,707 T0017: WARN  support post-session-prolog session pass ''
2024-01-06 23:08:42,710 T0018: WARN  #### gw2  
2024-01-06 23:08:42,710 T0018: WARN  support post-session-prolog session pass ''
2024-01-06 23:09:31,215 T0071: INFO  #### gw2  
2024-01-06 23:09:31,215 T0071: INFO  support pre-module-prolog routing/VRF/test_vrf_scale.py  ''
2024-01-06 23:09:31,217 T0072: INFO  #### gw2  
2024-01-06 23:09:31,217 T0072: INFO  support pre-module-prolog routing/VRF/test_vrf_scale.py  ''
2024-01-06 23:32:07,247 T0117: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:32:07,248 T0117: INFO  support post-module-prolog routing/VRF/test_vrf_scale.py Pass ''
2024-01-06 23:32:07,250 T0118: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:32:07,250 T0118: INFO  support post-module-prolog routing/VRF/test_vrf_scale.py Pass ''
2024-01-06 23:32:43,533 T0142: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:32:43,534 T0142: INFO  support pre-function-prolog test_vrf_scale  ''
2024-01-06 23:32:43,537 T0143: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:32:43,537 T0143: INFO  support pre-function-prolog test_vrf_scale  ''
2024-01-06 23:32:43,550 T0144: INFO  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:32:43,550 T0144: INFO  support post-function-prolog test_vrf_scale Pass ''
2024-01-06 23:32:43,552 T0145: INFO  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:32:43,552 T0145: INFO  support post-function-prolog test_vrf_scale Pass ''
2024-01-06 23:36:05,524 T0000: ERROR #### gw2 WARN routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:36:05,524 T0000: ERROR Traceback (most recent call last):
2024-01-06 23:36:05,524 T0000: ERROR   File "/repo/spytest/net.py", line 1910, in _try
2024-01-06 23:36:05,524 T0000: ERROR     output = hndl.send_command_new(fcli, new_cmd, expect_string,
2024-01-06 23:36:05,524 T0000: ERROR   File "/repo/spytest/access/netmiko_connection.py", line 725, in send_command_new
2024-01-06 23:36:05,524 T0000: ERROR     raise IOError(self.dmsg_str(dbg_msg, msg1))
2024-01-06 23:36:05,524 T0000: ERROR OSError: Prompt Not Detected in DF 2.0: 'admin@sonic:\~\$'
2024-01-06 23:36:05,524 T0000: ERROR =======================FASTER-CLI-DBG===================
2024-01-06 23:36:05,524 T0000: ERROR command_string: show vrf<LF>
2024-01-06 23:36:05,524 T0000: ERROR search_pattern: admin@sonic:\~\$
2024-01-06 23:36:05,524 T0000: ERROR cmd_issued: False
2024-01-06 23:36:05,524 T0000: ERROR CMP-OUT: show vrf<LF><LF>
2024-01-06 23:36:05,524 T0000: ERROR CMP-CMD: show vrf<LF>
2024-01-06 23:36:05,524 T0000: ERROR ECHOED OUTPUT: <LF>
2024-01-06 23:36:05,524 T0000: ERROR CMP-PROMPT: admin@sonic:\~\$
2024-01-06 23:36:05,524 T0000: ERROR CMP-OUTPUT: 
2024-01-06 23:36:05,524 T0000: ERROR CMP-OUTPUT: 
2024-01-06 23:36:05,524 T0000: ERROR Read Data: show vrf
2024-01-06 23:36:05,524 T0000: ERROR =========================================================
2024-01-06 23:36:05,524 T0000: ERROR StackTraceCallStack:
2024-01-06 23:36:05,524 T0000: ERROR [0] spytest/net.py:2138 _send_command output = self._try(access, line, fcli, cmd, expect,
2024-01-06 23:36:05,524 T0000: ERROR [1] spytest/net.py:6125 _send_cmd_opts output = self._send_command(access, cmd, expected_prompt,
2024-01-06 23:36:05,524 T0000: ERROR Truncated...
2024-01-06 23:39:15,497 T0146: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:39:15,497 T0146: WARN  support pre-function-epilog test_vrf_scale Fail 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-06 23:39:15,499 T0147: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:39:15,499 T0147: WARN  support pre-function-epilog test_vrf_scale Fail 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-06 23:39:16,260 T0148: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:39:16,260 T0148: WARN  support post-function-epilog test_vrf_scale ignore 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-06 23:39:16,262 T0149: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-06 23:39:16,262 T0149: WARN  support post-function-epilog test_vrf_scale ignore 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-06 23:39:22,693 T0155: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:39:22,694 T0155: INFO  support pre-function-prolog test_vrf_route_leak  ''
2024-01-06 23:39:22,698 T0156: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:39:22,698 T0156: INFO  support pre-function-prolog test_vrf_route_leak  ''
2024-01-06 23:41:23,956 T0161: INFO  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_route_leak
2024-01-06 23:41:23,956 T0161: INFO  support pre-function-epilog test_vrf_route_leak Pass 'Test case passed'
2024-01-06 23:41:23,958 T0162: INFO  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_route_leak
2024-01-06 23:41:23,959 T0162: INFO  support pre-function-epilog test_vrf_route_leak Pass 'Test case passed'
2024-01-06 23:41:23,971 T0163: INFO  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_route_leak
2024-01-06 23:41:23,972 T0163: INFO  support post-function-epilog test_vrf_route_leak Pass 'Test case passed'
2024-01-06 23:41:23,975 T0164: INFO  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_route_leak
2024-01-06 23:41:23,975 T0164: INFO  support post-function-epilog test_vrf_route_leak Pass 'Test case passed'
2024-01-06 23:41:31,444 T0170: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:41:31,444 T0170: INFO  support pre-function-prolog test_vrf_bgp  ''
2024-01-06 23:41:31,448 T0171: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:41:31,448 T0171: INFO  support pre-function-prolog test_vrf_bgp  ''
2024-01-06 23:54:08,498 T0564: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_bgp
2024-01-06 23:54:08,499 T0564: WARN  support pre-function-epilog test_vrf_bgp Fail 'Test case Failed.'
2024-01-06 23:54:08,502 T0565: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_bgp
2024-01-06 23:54:08,502 T0565: WARN  support pre-function-epilog test_vrf_bgp Fail 'Test case Failed.'
2024-01-06 23:54:08,900 T0566: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_bgp
2024-01-06 23:54:08,901 T0566: WARN  support post-function-epilog test_vrf_bgp ignore 'Test case Failed.'
2024-01-06 23:54:08,902 T0567: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_bgp
2024-01-06 23:54:08,903 T0567: WARN  support post-function-epilog test_vrf_bgp ignore 'Test case Failed.'
2024-01-06 23:54:16,646 T0573: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:54:16,646 T0573: INFO  support pre-function-prolog test_vrf_reload  ''
2024-01-06 23:54:16,650 T0574: INFO  #### gw2  routing/VRF/test_vrf_scale.py
2024-01-06 23:54:16,650 T0574: INFO  support pre-function-prolog test_vrf_reload  ''
2024-01-06 23:56:59,532 T0000: WARN  #### gw2 IGNORED ERROR routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-06 23:56:59,532 T0000: WARN  Skipped error checking but detected pattern: containing_python_traceback command: sudo -s fast-reboot
2024-01-07 00:00:46,888 T0000: ERROR #### gw2 WARN routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:00:46,888 T0000: ERROR Traceback (most recent call last):
2024-01-07 00:00:46,888 T0000: ERROR   File "/repo/spytest/net.py", line 1910, in _try
2024-01-07 00:00:46,888 T0000: ERROR     output = hndl.send_command_new(fcli, new_cmd, expect_string,
2024-01-07 00:00:46,888 T0000: ERROR   File "/repo/spytest/access/netmiko_connection.py", line 725, in send_command_new
2024-01-07 00:00:46,888 T0000: ERROR     raise IOError(self.dmsg_str(dbg_msg, msg1))
2024-01-07 00:00:46,888 T0000: ERROR OSError: Prompt Not Detected in DF 2.0: 'admin@sonic:\~\$'
2024-01-07 00:00:46,888 T0000: ERROR =======================FASTER-CLI-DBG===================
2024-01-07 00:00:46,888 T0000: ERROR command_string: show vrf<LF>
2024-01-07 00:00:46,888 T0000: ERROR search_pattern: admin@sonic:\~\$
2024-01-07 00:00:46,888 T0000: ERROR cmd_issued: False
2024-01-07 00:00:46,888 T0000: ERROR CMP-OUT: show vrf<LF><LF>
2024-01-07 00:00:46,889 T0000: ERROR CMP-CMD: show vrf<LF>
2024-01-07 00:00:46,889 T0000: ERROR ECHOED OUTPUT: <LF>
2024-01-07 00:00:46,889 T0000: ERROR CMP-PROMPT: admin@sonic:\~\$
2024-01-07 00:00:46,889 T0000: ERROR CMP-OUTPUT: 
2024-01-07 00:00:46,889 T0000: ERROR CMP-OUTPUT: 
2024-01-07 00:00:46,889 T0000: ERROR Read Data: show vrf
2024-01-07 00:00:46,889 T0000: ERROR =========================================================
2024-01-07 00:00:46,889 T0000: ERROR StackTraceCallStack:
2024-01-07 00:00:46,889 T0000: ERROR [0] spytest/net.py:2138 _send_command output = self._try(access, line, fcli, cmd, expect,
2024-01-07 00:00:46,889 T0000: ERROR [1] spytest/net.py:6125 _send_cmd_opts output = self._send_command(access, cmd, expected_prompt,
2024-01-07 00:00:46,889 T0000: ERROR Truncated...
2024-01-07 00:04:08,675 T0575: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:04:08,675 T0575: WARN  support pre-function-epilog test_vrf_reload Fail 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-07 00:04:08,676 T0576: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:04:08,677 T0576: WARN  support pre-function-epilog test_vrf_reload Fail 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-07 00:04:09,463 T0577: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:04:09,463 T0577: WARN  support post-function-epilog test_vrf_reload ignore 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-07 00:04:09,464 T0578: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:04:09,465 T0578: WARN  support post-function-epilog test_vrf_reload ignore 'Command 'show vrf' failed to give required prompt, recovered using CR'
2024-01-07 00:04:09,506 T0579: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:04:09,506 T0579: WARN  support pre-module-epilog routing/VRF/test_vrf_scale.py fail ''
2024-01-07 00:04:09,508 T0580: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_reload
2024-01-07 00:04:09,508 T0580: WARN  support pre-module-epilog routing/VRF/test_vrf_scale.py fail ''
2024-01-07 00:04:33,822 T0597: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-07 00:04:33,823 T0597: WARN  support post-module-epilog routing/VRF/test_vrf_scale.py fail ''
2024-01-07 00:04:33,826 T0598: WARN  #### gw2  routing/VRF/test_vrf_scale.py::test_vrf_scale
2024-01-07 00:04:33,826 T0598: WARN  support post-module-epilog routing/VRF/test_vrf_scale.py fail ''
2024-01-07 00:10:49,137 T0644: ERROR #### gw2 WARN 
2024-01-07 00:10:49,137 T0644: ERROR Traceback (most recent call last):
2024-01-07 00:10:49,137 T0644: ERROR   File "/repo/spytest/net.py", line 1910, in _try
2024-01-07 00:10:49,137 T0644: ERROR     output = hndl.send_command_new(fcli, new_cmd, expect_string,
2024-01-07 00:10:49,137 T0644: ERROR   File "/repo/spytest/access/netmiko_connection.py", line 725, in send_command_new
2024-01-07 00:10:49,137 T0644: ERROR     raise IOError(self.dmsg_str(dbg_msg, msg1))
2024-01-07 00:10:49,137 T0644: ERROR OSError: Prompt Not Detected in DF 2.0: '(sonic|sonic)#'
2024-01-07 00:10:49,137 T0644: ERROR =======================FASTER-CLI-DBG===================
2024-01-07 00:10:49,137 T0644: ERROR command_string: sudo vtysh<LF>
2024-01-07 00:10:49,137 T0644: ERROR search_pattern: (sonic|sonic)#
2024-01-07 00:10:49,137 T0644: ERROR cmd_issued: False
2024-01-07 00:10:49,138 T0644: ERROR CMP-OUT: sudo vtysh<LF><LF>
2024-01-07 00:10:49,138 T0644: ERROR CMP-CMD: sudo vtysh<LF>
2024-01-07 00:10:49,138 T0644: ERROR ECHOED OUTPUT: <LF>
2024-01-07 00:10:49,138 T0644: ERROR CMP-PROMPT: (sonic|sonic)#
2024-01-07 00:10:49,138 T0644: ERROR CMP-OUTPUT: 
2024-01-07 00:10:49,138 T0644: ERROR CMP-OUTPUT: 
2024-01-07 00:10:49,138 T0644: ERROR cmd_issued: True
2024-01-07 00:10:49,138 T0644: ERROR CMP-PROMPT: (sonic|sonic)#
2024-01-07 00:10:49,138 T0644: ERROR CMP-OUTPUT: Error response from daemon: Container 5f6f460a1b04709a47f81f0b0b1962e1da750198da0a6630cf0d2f3c79f4c2a1 is not running
2024-01-07 00:10:49,138 T0644: ERROR CMP-OUTPUT:  admin@sonic:~$ 
2024-01-07 00:10:49,138 T0644: ERROR CMP-OUTPUT: 
2024-01-07 00:10:49,138 T0644: ERROR Truncated...
2024-01-07 00:10:51,859 T0644: WARN  #### gw2  
2024-01-07 00:10:51,859 T0644: WARN  support function  ConfigFail 'Command 'sudo vtysh' failed to give required prompt, recovered using CR'
