#,Feature,TestCase,Result,ResultType,ExecutedOn,Description,Function,Module,Devices,KnownIssue
1,Regression,FtOpSoSwLagFn042,Pass,Mapped,2023-12-30 03:38:54,Test case passed,test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
2,Regression,FtOpSoSwLagFn041,Pass,Mapped,2023-12-30 03:38:54,Test case passed,test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
3,PortChannel Config Enhancements,FtOpSoSwPominFn007,Pass,Mapped,2023-12-30 03:39:14,Test case passed,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,switching/test_portchannel.py,"V1, V2",
4,Regression,ft_lldp_LocManAddrLen,Fail,Mapped,2023-12-30 03:42:51,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrLen,system/test_lldp.py,"V1, V2",
5,Regression,ft_lldp_LocManAddrlfld,Fail,Mapped,2023-12-30 03:42:51,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrlfld,system/test_lldp.py,"V1, V2",
6,Regression,ft_lldp_LocManAddrEntry,Fail,Mapped,2023-12-30 03:42:51,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrEntry,system/test_lldp.py,"V1, V2",
7,Regression,ft_lldp_ConfigManAddrEntry,Fail,Mapped,2023-12-30 03:42:52,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_ConfigManAddrEntry,system/test_lldp.py,"V1, V2",
8,Regression,ft_lldp_lldplocportid,Fail,Mapped,2023-12-30 03:42:52,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocportid,system/test_lldp.py,"V1, V2",
9,Regression,ft_lldp_lldplocsysname,Fail,Mapped,2023-12-30 03:42:52,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysname,system/test_lldp.py,"V1, V2",
10,Regression,ft_lldp_lldplocsysdesc,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysdesc,system/test_lldp.py,"V1, V2",
11,SNMP Agent Optimization,ft_snmp_lldp_prem_manaddr_table,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_rem_man_addr_table,system/test_lldp.py,"V1, V2",
12,Regression,FtOpSoSwlldpFn011,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
13,Regression,FtOpSoSwlldpFn010,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
14,Regression,FtOpSoSwlldpFn009,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
15,Regression,FtOpSoSwlldpFn008,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
16,Regression,FtOpSoSwlldpFn004,Fail,Mapped,2023-12-30 03:42:53,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
17,Regression,FtOpSoSwlldpFn013,Fail,Mapped,2023-12-30 03:42:54,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_docker_restart,system/test_lldp.py,"V1, V2",
18,Regression,lldp_verify_counters,Fail,Mapped,2023-12-30 03:42:54,module configuration failed. LLDP neighbors information is not found after polling @5445,test_lldp_verify_counters,system/test_lldp.py,"V1, V2",
19,Regression,ft_lldp_with_remote_server,Fail,Mapped,2023-12-30 03:42:54,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_with_remote_server,system/test_lldp.py,"V1, V2",
20,Regression,ft_ssh_service_disable,Pass,Mapped,2023-12-30 03:45:27,Test case passed,test_ft_ssh_service_disable,system/test_ssh.py,"V1, V2",
21,Control Plane ACL,test_ft_controlplane_acl_service_sshv6,ScriptError,Mapped,2023-12-30 03:48:06,Exception SPyTestCmdException Command Exception: sshpass -p 'YourPaSsWoRd' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 admin@2.2.3.1 sudo show vlan config in file /spytest/net.py at line 1636,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
22,Control Plane ACL,test_ft_controlplane_acl_service_sshv4,ScriptError,Mapped,2023-12-30 03:48:06,Exception SPyTestCmdException Command Exception: sshpass -p 'YourPaSsWoRd' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 admin@2.2.3.1 sudo show vlan config in file /spytest/net.py at line 1636,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
23,Control Plane ACL,test_ft_controlplane_acl_service_snmp,ScriptError,Mapped,2023-12-30 03:48:06,Exception SPyTestCmdException Command Exception: sshpass -p 'YourPaSsWoRd' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 admin@2.2.3.1 sudo show vlan config in file /spytest/net.py at line 1636,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
24,Regression,ft_ssh_add_user_verify,ScriptError,Mapped,2023-12-30 03:48:06,Exception SPyTestCmdException Command Exception: sshpass -p 'YourPaSsWoRd' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 admin@2.2.3.1 sudo show vlan config in file /spytest/net.py at line 1636,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
25,Regression,CETA_SONIC_67575,Pass,Mapped,2023-12-30 03:48:27,Test case passed,test_ft_verify_logs_at_the_time_of_ssh_login_success,system/test_ssh.py,"V1, V2",
26,Regression,FtOpSoSyInIpFn002,Fail,Mapped,2023-12-30 03:55:18,interface is down on DUT ['Ethernet16'],test_ft_port_fn_verify_shut_noshut,system/test_interface.py,"V1, V2",
