2023-12-29 01:32:17,990 T0000: NOTICE WORKER = gw5
2023-12-29 01:32:17,990 T0000: NOTICE using testbed file /data/work/logs/docker-master-443064-l2/testbed_1_1_2.yaml
2023-12-29 01:32:17,990 T0000: NOTICE Execution Start Time: 2023-12-29 01:32:17.988870
2023-12-29 01:32:17,990 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-443064-l2/gw5
2023-12-29 01:32:18,481 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-29 01:32:18,481 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 40.0%
2023-12-29 01:32:18,481 T0000: NOTICE ROOT_PATH: /repo
2023-12-29 01:32:18,481 T0000: NOTICE Python: 3.8.10
2023-12-29 01:32:18,481 T0000: NOTICE Topology unknown: D1T1:4
2023-12-29 01:32:18,481 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-29 01:32:18,481 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-29-01-29-47 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-443064-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-443064-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-443064-l2 --noop --feature-group master
2023-12-29 01:32:19,091 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2023-12-29 01:32:19,092 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-29 01:32:19,092 T0000: WARN  Registering Topology
2023-12-29 01:32:19,107 T0000: INFO  Connecting all devices
2023-12-29 01:32:19,110 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/9', '1/10', '1/11', '1/12'] skip: False
2023-12-29 01:32:19,322 T0002: INFO  [D1-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2023-12-29 01:32:19,322 T0002: INFO  [D1-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2023-12-29 01:32:20,123 T0000: INFO  TG Scapy Init
2023-12-29 01:32:20,123 T0000: INFO  TG Base Init skip: False
2023-12-29 01:32:20,133 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-29 01:32:20,320 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_29_01_32_20_159522/gw5/default.log
2023-12-29 01:32:20,328 T0000: DEBUG REQ: tg_connect(port_list=['1/9', '1/10', '1/11', '1/12'])
2023-12-29 01:32:24,695 T0002: DEBUG [D1-V3] Connected ...
2023-12-29 01:32:25,518 T0002: INFO  [D1-V3] Prompt at the connection start: 'admin@V3:~$' 
2023-12-29 01:32:25,522 T0002: AUDIT [D1-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-29 01:32:25,931 T0002: INFO  [D1-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-29 01:32:26,188 T0002: INFO  [D1-V3]  01:32:26 up 21 days,  2:35,  1 user,  load average: 13.83, 16.53, 11.30
2023-12-29 01:32:26,189 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:26,196 T0002: AUDIT [D1-V3] cat /proc/uptime
2023-12-29 01:32:26,602 T0002: INFO  [D1-V3] FCMD: cat /proc/uptime
2023-12-29 01:32:26,861 T0002: INFO  [D1-V3] 1823707.39 143794167.37
2023-12-29 01:32:26,862 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:26,866 T0002: INFO  [D1-V3] UPTIME: 1823707.39
2023-12-29 01:32:26,869 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:26,982 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12"}, "status": 1}
2023-12-29 01:32:26,990 T0000: INFO  TG Connection: Success
2023-12-29 01:32:26,991 T0000: INFO  TG Connect...done
2023-12-29 01:32:27,274 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:27,936 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:32:27,936 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:27,939 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:27,941 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:27,942 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:32,947 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:33,354 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:33,964 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:32:33,965 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:33,967 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:33,969 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:33,969 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:38,974 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:39,382 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:40,092 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:32:40,092 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:40,093 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:40,094 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:40,094 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:45,098 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:45,505 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:46,116 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:32:46,116 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:46,118 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:46,120 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:46,120 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:51,126 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:51,533 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:52,144 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:32:52,144 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:52,147 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:52,149 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:52,149 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:32:57,153 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:57,560 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:58,170 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:32:58,170 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:32:58,173 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:32:58,175 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:32:58,175 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:03,178 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:03,585 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:04,196 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:04,196 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:04,199 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:04,201 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:04,201 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:09,206 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:09,613 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:10,224 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:10,225 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:10,228 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:10,230 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:10,230 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:15,234 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:15,641 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:16,304 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:16,304 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:16,307 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:16,308 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:16,308 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:21,314 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:21,721 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:22,381 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:22,382 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:22,382 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:22,383 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:22,383 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:27,389 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:27,796 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:28,507 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:28,507 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:28,510 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:28,512 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:28,512 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:33,518 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:33,925 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:34,536 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:34,536 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:34,539 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:34,541 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:34,541 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:39,546 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:39,955 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:40,565 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:40,565 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:40,567 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:40,569 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:40,569 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:45,575 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:45,983 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:46,695 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:46,696 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:46,698 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:46,700 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:46,701 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:51,706 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:52,114 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:52,725 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:52,725 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:52,728 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:52,730 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:52,730 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:33:57,736 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:58,143 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:58,754 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:33:58,754 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:33:58,757 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:33:58,759 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:33:58,759 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:03,761 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:04,165 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:04,824 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:34:04,824 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:34:04,826 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:04,828 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:04,828 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:09,834 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:10,240 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:11,001 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:34:11,001 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:34:11,004 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:11,006 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:11,006 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:16,010 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:16,419 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:17,179 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:34:17,179 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:34:17,182 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:17,184 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:17,184 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:22,185 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:22,592 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:23,304 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-29 01:34:23,305 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:34:23,310 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-29 01:34:23,311 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-29 01:34:23,311 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-29 01:34:28,315 T0002: ERROR [D1-V3] Failed to read hostname from vtysh - assuming sonic
2023-12-29 01:34:28,316 T0002: INFO  [D1-V3] Base Prompt: sonic
2023-12-29 01:34:28,318 T0002: DEBUG [D1-V3] Wait for system ready Ref: 866
2023-12-29 01:34:28,723 T0002: INFO  [D1-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-29 01:34:28,982 T0002: INFO  [D1-V3] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-29 01:34:28,982 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:34:28,986 T0002: WARN  [D1-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-29 01:34:28,987 T0002: INFO  [D1-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-29 01:34:32,810 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-29 01:34:32,812 T0002: INFO  [D1-V3] 
2023-12-29 01:34:32,812 T0002: INFO  [D1-V3] Remote CMD: 'show platform summary'
2023-12-29 01:34:32,813 T0002: INFO  [D1-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-29 01:34:32,813 T0002: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-29 01:34:32,813 T0002: INFO  [D1-V3]     from show.main import cli
2023-12-29 01:34:32,813 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-29 01:34:32,813 T0002: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-29 01:34:32,813 T0002: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:32,814 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-29 01:34:32,814 T0002: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-29 01:34:32,814 T0002: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-29 01:34:32,814 T0002: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-29 01:34:32,814 T0002: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:32,814 T0002: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3] 
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3] Remote CMD: 'sudo show interfaces status '
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]     from show.main import cli
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-29 01:34:32,815 T0002: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-29 01:34:32,816 T0002: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-29 01:34:32,816 T0002: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-29 01:34:32,816 T0002: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-29 01:34:32,816 T0002: INFO  [D1-V3] 
2023-12-29 01:34:32,816 T0002: INFO  [D1-V3] admin@V3:~$ 
2023-12-29 01:34:32,816 T0002: ERROR [D1-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-29 01:34:32,817 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-29 01:34:32,817 T0002: ERROR [D1-V3] Failed to connect to device
2023-12-29 01:34:32,818 T0000: ERROR Failed to connect (['V3'])
2023-12-29 01:34:32,818 T0000: INFO  --FINISH--RUN--4 @559
