ordering items took 0:00:01
Tests considered 69 and ignored 320
2023-12-30 01:56:27,147 T0000: NOTICE WORKER = gw6
2023-12-30 01:56:27,147 T0000: NOTICE using testbed file /data/work/logs/docker-master-443710-l2/testbed_1_1_3.yaml
2023-12-30 01:56:27,147 T0000: NOTICE Execution Start Time: 2023-12-30 01:56:27.145378
2023-12-30 01:56:27,147 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-443710-l2/gw6
2023-12-30 01:56:27,677 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-30 01:56:27,677 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 41.5%
2023-12-30 01:56:27,677 T0000: NOTICE ROOT_PATH: /repo
2023-12-30 01:56:27,677 T0000: NOTICE Python: 3.8.10
2023-12-30 01:56:27,677 T0000: NOTICE Topology unknown: D1T1:4
2023-12-30 01:56:27,677 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-30 01:56:27,678 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-30-01-53-56 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-443710-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-443710-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-443710-l2 --noop --feature-group master
2023-12-30 01:56:28,430 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2023-12-30 01:56:28,430 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-30 01:56:28,430 T0000: WARN  Registering Topology
2023-12-30 01:56:28,446 T0000: INFO  Connecting all devices
2023-12-30 01:56:28,450 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/13', '1/14', '1/15', '1/16'] skip: False
2023-12-30 01:56:28,660 T0002: INFO  [D1-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2023-12-30 01:56:28,660 T0002: INFO  [D1-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2023-12-30 01:56:29,483 T0000: INFO  TG Scapy Init
2023-12-30 01:56:29,484 T0000: INFO  TG Base Init skip: False
2023-12-30 01:56:29,492 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-30 01:56:29,850 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_30_01_56_29_547353/gw6/default.log
2023-12-30 01:56:29,861 T0000: DEBUG REQ: tg_connect(port_list=['1/13', '1/14', '1/15', '1/16'])
2023-12-30 01:56:34,234 T0002: DEBUG [D1-V4] Connected ...
2023-12-30 01:56:35,057 T0002: INFO  [D1-V4] Prompt at the connection start: 'admin@V4:~$' 
2023-12-30 01:56:35,059 T0002: AUDIT [D1-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-30 01:56:35,466 T0002: INFO  [D1-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-30 01:56:35,722 T0002: INFO  [D1-V4]  01:56:35 up 22 days,  2:59,  1 user,  load average: 13.27, 20.14, 13.77
2023-12-30 01:56:35,722 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:56:35,728 T0002: AUDIT [D1-V4] cat /proc/uptime
2023-12-30 01:56:36,134 T0002: INFO  [D1-V4] FCMD: cat /proc/uptime
2023-12-30 01:56:36,391 T0002: INFO  [D1-V4] 1911579.21 150705086.04
2023-12-30 01:56:36,391 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:56:36,393 T0002: INFO  [D1-V4] UPTIME: 1911579.21
2023-12-30 01:56:36,394 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:36,802 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:37,413 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:56:37,413 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:56:37,416 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:37,419 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:56:37,419 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:56:37,714 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2023-12-30 01:56:37,725 T0000: INFO  TG Connection: Success
2023-12-30 01:56:37,725 T0000: INFO  TG Connect...done
2023-12-30 01:56:42,422 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:42,829 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:43,440 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:56:43,441 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:56:43,443 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:43,445 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:56:43,445 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:56:48,450 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:48,855 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:49,461 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:56:49,461 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:56:49,463 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:49,464 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:56:49,464 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:56:54,466 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:54,873 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:55,483 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:56:55,484 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:56:55,486 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:56:55,488 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:56:55,489 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:00,494 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:00,900 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:01,510 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:01,510 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:01,513 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:01,516 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:01,516 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:06,518 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:06,926 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:07,537 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:07,537 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:07,539 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:07,542 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:07,542 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:12,546 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:12,953 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:13,614 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:13,614 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:13,617 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:13,619 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:13,619 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:18,621 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:19,027 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:19,639 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:19,639 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:19,643 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:19,646 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:19,646 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:24,652 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:25,059 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:25,670 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:25,670 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:25,673 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:25,675 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:25,675 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:30,678 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:31,086 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:31,697 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:31,697 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:31,700 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:31,702 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:31,702 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:36,706 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:37,113 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:37,724 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:37,724 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:37,725 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:37,727 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:37,727 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:42,730 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:43,139 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:43,750 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:43,750 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:43,753 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:43,755 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:43,755 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:48,761 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:49,167 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:49,777 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:49,777 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:49,780 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:49,782 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:49,782 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:57:54,788 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:55,196 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:55,806 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:57:55,807 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:57:55,809 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:57:55,810 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:57:55,810 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:00,816 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:01,224 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:01,834 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:58:01,835 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:01,837 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:01,839 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:58:01,840 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:06,845 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:07,252 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:07,858 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:58:07,859 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:07,860 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:07,861 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:58:07,861 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:12,866 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:13,274 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:13,937 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:58:13,937 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:13,938 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:13,939 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:58:13,939 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:18,945 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:19,350 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:20,210 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:58:20,211 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:20,212 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:20,214 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:58:20,214 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:25,218 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:25,626 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:26,287 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:58:26,287 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:26,290 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:26,292 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:58:26,293 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:31,298 T0002: AUDIT [D1-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:31,708 T0002: INFO  [D1-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:32,470 T0002: INFO  [D1-V4] Error response from daemon: No such container: bgp
2023-12-30 01:58:32,470 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:32,474 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-30 01:58:32,477 T0002: WARN  [D1-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-30 01:58:32,477 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-30 01:58:37,484 T0002: ERROR [D1-V4] Failed to read hostname from vtysh - assuming sonic
2023-12-30 01:58:37,487 T0002: INFO  [D1-V4] Base Prompt: sonic
2023-12-30 01:58:37,489 T0002: DEBUG [D1-V4] Wait for system ready Ref: 866
2023-12-30 01:58:37,895 T0002: INFO  [D1-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-30 01:58:38,152 T0002: INFO  [D1-V4] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-30 01:58:38,152 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:38,157 T0002: WARN  [D1-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-30 01:58:38,158 T0002: INFO  [D1-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-30 01:58:41,991 T0002: WARN  [D1-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4] 
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4] Remote CMD: 'show platform summary'
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4]     from show.main import cli
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-30 01:58:41,992 T0002: INFO  [D1-V4]     if is_gearbox_configured():
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4]     app_db.connect(app_db.APPL_DB)
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-30 01:58:41,993 T0002: INFO  [D1-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4] 
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4] Remote CMD: 'sudo show interfaces status '
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4]     from show.main import cli
2023-12-30 01:58:41,994 T0002: INFO  [D1-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]     if is_gearbox_configured():
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]     app_db.connect(app_db.APPL_DB)
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-30 01:58:41,995 T0002: INFO  [D1-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-30 01:58:41,996 T0002: INFO  [D1-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-30 01:58:41,996 T0002: INFO  [D1-V4] 
2023-12-30 01:58:41,996 T0002: INFO  [D1-V4] admin@V4:~$ 
2023-12-30 01:58:41,997 T0002: ERROR [D1-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-30 01:58:41,997 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-30 01:58:41,998 T0002: ERROR [D1-V4] Failed to connect to device
2023-12-30 01:58:41,998 T0000: ERROR Failed to connect (['V4'])
2023-12-30 01:58:41,999 T0000: INFO  --FINISH--RUN--4 @559
