2023-12-27 00:42:17,964 T0015: INFO  Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2023-12-27 00:42:17,965 T0015: INFO  TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2023-12-27 00:42:23,177 T0015: DEBUG Connected ...
2023-12-27 00:42:24,012 T0015: INFO  Prompt at the connection start: 'admin@V4:~$' 
2023-12-27 00:42:24,431 T0015: INFO  FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-27 00:42:24,697 T0015: INFO   00:42:24 up 19 days,  1:44,  1 user,  load average: 31.69, 20.92, 11.90
2023-12-27 00:42:24,698 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:25,108 T0015: INFO  FCMD: cat /proc/uptime
2023-12-27 00:42:25,364 T0015: INFO  1647861.71 129976335.67
2023-12-27 00:42:25,364 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:25,366 T0015: INFO  UPTIME: 1647861.71
2023-12-27 00:42:25,780 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:26,395 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:42:26,396 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:26,398 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:26,400 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:42:31,813 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:32,477 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:42:32,477 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:32,483 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:32,486 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:42:37,905 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:38,522 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:42:38,523 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:38,529 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:38,536 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:42:43,953 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:44,719 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:42:44,719 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:44,722 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:44,724 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:42:50,136 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:50,746 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:42:50,747 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:50,749 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:50,751 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:42:56,165 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:56,782 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:42:56,782 T0015: INFO  admin@V4:~$ 
2023-12-27 00:42:56,786 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:42:56,789 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:02,207 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:02,869 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:02,870 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:02,872 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:02,873 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:08,286 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:09,047 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:09,047 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:09,049 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:09,052 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:14,461 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:15,171 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:15,172 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:15,173 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:15,173 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:20,586 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:21,246 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:21,246 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:21,249 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:21,251 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:26,660 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:27,325 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:27,325 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:27,327 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:27,329 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:32,737 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:33,446 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:33,447 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:33,448 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:33,450 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:38,862 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:39,523 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:39,524 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:39,527 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:39,529 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:44,940 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:45,551 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:45,551 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:45,553 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:45,555 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:50,967 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:51,577 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:51,577 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:51,579 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:51,580 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:43:56,992 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:57,605 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:43:57,605 T0015: INFO  admin@V4:~$ 
2023-12-27 00:43:57,610 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:43:57,611 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:03,027 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:03,688 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:44:03,688 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:03,691 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:03,693 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:09,105 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:09,717 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:44:09,717 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:09,721 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:09,723 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:15,135 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:15,744 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:44:15,744 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:15,748 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:15,749 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:21,164 T0015: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:21,776 T0015: INFO  Error response from daemon: No such container: bgp
2023-12-27 00:44:21,777 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:21,782 T0015: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:21,784 T0015: WARN  Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:26,798 T0015: ERROR Failed to read hostname from vtysh - assuming sonic
2023-12-27 00:44:26,800 T0015: INFO  Base Prompt: sonic
2023-12-27 00:44:26,801 T0015: DEBUG Wait for system ready Ref: 866
2023-12-27 00:44:27,206 T0015: INFO  FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-27 00:44:27,464 T0015: INFO  md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-27 00:44:27,465 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:27,470 T0015: INFO  MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-27 00:44:27,472 T0015: INFO  Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-27 00:44:27,474 T0015: INFO  Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V4): /tmp/spytest-helper.py
2023-12-27 00:44:27,500 T0015: ERROR No mgmt IP
2023-12-27 00:44:27,507 T0015: INFO  Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-27 00:44:27,676 T0015: INFO  FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-27 00:44:27,932 T0015: INFO  4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-27 00:44:27,933 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:27,936 T0015: INFO  Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-27 00:44:27,937 T0015: INFO  SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-27 00:44:30,545 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:30,548 T0015: WARN  Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-27 00:44:30,549 T0015: INFO  SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:44:34,379 T0015: WARN  Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:44:34,389 T0015: INFO  
2023-12-27 00:44:34,390 T0015: INFO  Remote CMD: 'show platform summary'
2023-12-27 00:44:34,390 T0015: INFO  Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-27 00:44:34,390 T0015: INFO    File "/usr/local/bin/show", line 5, in <module>
2023-12-27 00:44:34,390 T0015: INFO      from show.main import cli
2023-12-27 00:44:34,390 T0015: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-27 00:44:34,390 T0015: INFO      if is_gearbox_configured():
2023-12-27 00:44:34,390 T0015: INFO         ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:44:34,390 T0015: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-27 00:44:34,390 T0015: INFO      app_db.connect(app_db.APPL_DB)
2023-12-27 00:44:34,390 T0015: INFO    File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-27 00:44:34,390 T0015: INFO      return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-27 00:44:34,391 T0015: INFO             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:44:34,391 T0015: INFO  RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-27 00:44:34,391 T0015: INFO  
2023-12-27 00:44:34,391 T0015: INFO  Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-27 00:44:34,391 T0015: INFO  Remote CMD: 'sudo show interfaces status '
2023-12-27 00:44:34,391 T0015: INFO  Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-27 00:44:34,391 T0015: INFO    File "/usr/local/bin/show", line 5, in <module>
2023-12-27 00:44:34,391 T0015: INFO      from show.main import cli
2023-12-27 00:44:34,392 T0015: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-27 00:44:34,392 T0015: INFO      if is_gearbox_configured():
2023-12-27 00:44:34,392 T0015: INFO         ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:44:34,392 T0015: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-27 00:44:34,392 T0015: INFO      app_db.connect(app_db.APPL_DB)
2023-12-27 00:44:34,392 T0015: INFO    File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-27 00:44:34,392 T0015: INFO      return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-27 00:44:34,392 T0015: INFO             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:44:34,392 T0015: INFO  RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-27 00:44:34,393 T0015: INFO  
2023-12-27 00:44:34,393 T0015: INFO  admin@V4:~$ 
2023-12-27 00:44:34,394 T0015: ERROR Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:44:34,432 T0011: ERROR Failed to connect to device
