2024-01-02 01:46:47,488 T0002: INFO  Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2024-01-02 01:46:47,489 T0002: INFO  TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2024-01-02 01:46:52,845 T0002: DEBUG Connected ...
2024-01-02 01:46:53,672 T0002: INFO  Prompt at the connection start: 'admin@V4:~$' 
2024-01-02 01:46:54,082 T0002: INFO  FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-02 01:46:54,339 T0002: INFO   01:46:54 up 25 days,  2:51,  1 user,  load average: 30.94, 36.11, 22.15
2024-01-02 01:46:54,340 T0002: INFO  admin@V4:~$ 
2024-01-02 01:46:54,757 T0002: INFO  FCMD: cat /proc/uptime
2024-01-02 01:46:55,391 T0002: INFO  2170261.50 171049878.90
2024-01-02 01:46:55,407 T0002: INFO  admin@V4:~$ 
2024-01-02 01:46:55,727 T0002: INFO  UPTIME: 2170261.50
2024-01-02 01:46:56,070 T0000: INFO  
2024-01-02 01:46:56,070 T0000: INFO  ================== batch/test_spytest_infra_1.py::test_spytest_infra_first ==================
2024-01-02 01:46:56,077 T0000: INFO  Report():batch/test_spytest_infra_1.py::test_spytest_infra_first 0:00:00 module configuration failed.  @5445
2024-01-02 01:46:56,416 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-02 01:46:57,027 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-02 01:46:57,028 T0002: INFO  admin@V4:~$ 
2024-01-02 01:46:57,030 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-02 01:46:57,033 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
