#,Feature,TestCase,Result,ResultType,ExecutedOn,Description,Function,Module,Devices,KnownIssue
1,Regression,ft_add_unknownvlan_interface,Pass,Mapped,2023-12-27 02:56:16,Test case passed,test_ft_add_unknownvlan_interface,switching/test_vlan.py,"V3, V4",
2,Regression,ft_vlan_delete_with_member,Pass,Mapped,2023-12-27 02:56:29,Test case passed,test_ft_vlan_delete_with_member,switching/test_vlan.py,"V3, V4",
3,Regression,ft_vlan_trunk_tagged,Pass,Mapped,2023-12-27 02:57:55,Test case passed,test_ft_vlan_trunk_tagged,switching/test_vlan.py,"V3, V4",
4,Regression,ft_show_vlan_brief,Pass,Mapped,2023-12-27 02:57:55,Test case passed,test_ft_vlan_trunk_tagged,switching/test_vlan.py,"V3, V4",
5,warmboot,ft_reboot_fdb_fast_reboot,ScriptError,Mapped,2023-12-27 03:03:09,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
6,warmboot,ft_max_vlan_save_reload,ScriptError,Mapped,2023-12-27 03:03:09,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
7,warmboot,FtOpSoSysFRFn005,ScriptError,Mapped,2023-12-27 03:03:09,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
8,Regression,FtOpSoSyInIpFn002,Fail,Mapped,2023-12-27 03:10:14,interface is down on DUT ['Ethernet48'],test_ft_port_fn_verify_shut_noshut,system/test_interface.py,"V3, V4",
9,Regression,ft_lldp_LocManAddrLen,Fail,Mapped,2023-12-27 03:16:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrLen,system/test_lldp.py,"V3, V4",
10,Regression,ft_lldp_LocManAddrlfld,Fail,Mapped,2023-12-27 03:16:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrlfld,system/test_lldp.py,"V3, V4",
11,Regression,ft_lldp_LocManAddrEntry,Fail,Mapped,2023-12-27 03:16:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrEntry,system/test_lldp.py,"V3, V4",
12,Regression,ft_lldp_ConfigManAddrEntry,Fail,Mapped,2023-12-27 03:16:26,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_ConfigManAddrEntry,system/test_lldp.py,"V3, V4",
13,Regression,ft_lldp_lldplocportid,Fail,Mapped,2023-12-27 03:16:26,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocportid,system/test_lldp.py,"V3, V4",
14,Regression,ft_lldp_lldplocsysname,Fail,Mapped,2023-12-27 03:16:26,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysname,system/test_lldp.py,"V3, V4",
15,Regression,ft_lldp_lldplocsysdesc,Fail,Mapped,2023-12-27 03:16:27,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysdesc,system/test_lldp.py,"V3, V4",
16,SNMP Agent Optimization,ft_snmp_lldp_prem_manaddr_table,Fail,Mapped,2023-12-27 03:16:27,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_rem_man_addr_table,system/test_lldp.py,"V3, V4",
17,Regression,FtOpSoSwlldpFn011,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
18,Regression,FtOpSoSwlldpFn010,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
19,Regression,FtOpSoSwlldpFn009,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
20,Regression,FtOpSoSwlldpFn008,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
21,Regression,FtOpSoSwlldpFn004,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
22,Regression,FtOpSoSwlldpFn013,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_docker_restart,system/test_lldp.py,"V3, V4",
23,Regression,lldp_verify_counters,Fail,Mapped,2023-12-27 03:16:28,module configuration failed. LLDP neighbors information is not found after polling @5445,test_lldp_verify_counters,system/test_lldp.py,"V3, V4",
24,Regression,ft_lldp_with_remote_server,Fail,Mapped,2023-12-27 03:16:29,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_with_remote_server,system/test_lldp.py,"V3, V4",
